version: "3.9"
services:
  worker:
    build: .
    environment:
      APP_ID: $APP_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $7233484534:AAElm3P0GZGF8p4XKxRYpLV4ozw3F969-D0
      OWNER: $OWNER
      THUMBNAIL: $THUMBNAIL
